# Generated by Django 3.0 on 2023-03-14 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_acoustic_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f3', models.IntegerField()),
                ('f2', models.IntegerField()),
                ('f1', models.IntegerField()),
                ('f0', models.IntegerField()),
                ('backness', models.FloatField()),
                ('height', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('acoustic_measurements', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_acoustic_analysis.AcousticMeasurements')),
            ],
        ),
    ]
