# Generated by Django 3.1.1 on 2023-03-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diagram', '0006_auto_20230314_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagramcoordinates',
            name='f0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagramcoordinates',
            name='f1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagramcoordinates',
            name='f2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagramcoordinates',
            name='f3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
